version: "3.8"

services:
  app:
    image: php:8.3-fpm
    container_name: gauzeonde_app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:alpine
    container_name: gauzeonde_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: gauzeonde_postgres
    environment:
      POSTGRES_DB: gauzeonde
      POSTGRES_USER: gauzeonde
      POSTGRES_PASSWORD: secretpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: gauzeonde_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata: